import type { ApproximateDateValue, RectificationDraft, RectificationEvent } from './types';
const ENDPOINT = 'https://safircan.com/api/rectification';
export type RectificationApiError = 'auth' | 'validation' | 'network' | 'entitlement' | 'insufficient' | 'profile_incomplete';
export class RectificationRequestError extends Error { constructor(kind: RectificationApiError, public readonly fields: Record<string, string> = {}, public readonly missingFields: string[] = []) { super(kind); } }
type ApiEvent = { category: string; event_type: string; event_date: string | null; event_year: number | null; event_month: number | null; is_approximate: boolean; end_date: string | null; description: string | null };
function parseDate(value?: ApproximateDateValue) { if (!value || value.precision === 'unknown' || value.precision === 'not-applicable' || !value.value.trim()) return { event_date: null, event_year: null, event_month: null, is_approximate: false }; const parts = value.value.trim().split(/[./-]/).map(Number); if (value.precision === 'exact' && parts.length === 3) { const [day, month, year] = parts; return { event_date: `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`, event_year: year, event_month: month, is_approximate: value.isApproximate }; } if (value.precision === 'month-year' && parts.length === 2) return { event_date: null, event_year: parts[1], event_month: parts[0], is_approximate: value.isApproximate }; const year = parts.at(-1); return { event_date: null, event_year: Number.isInteger(year) ? year! : null, event_month: null, is_approximate: value.isApproximate }; }
function event(category: string, item: RectificationEvent): ApiEvent { const date = parseDate(item.date); const end = parseDate(item.endDate); const location = item.from || item.to ? `${item.from ?? ''} → ${item.to ?? ''}`.trim() : ''; const description = [location, item.description].filter(Boolean).join(' • '); return { category, event_type: item.type, ...date, end_date: end.event_date, description: description || null }; }
function dated(category: string, type: string, date: ApproximateDateValue): ApiEvent | null { if (date.precision === 'unknown' || date.precision === 'not-applicable') return null; return { category, event_type: type, ...parseDate(date), end_date: null, description: null }; }
export function normalizeRectificationDraft(draft: RectificationDraft) {
  const events: ApiEvent[] = [];
  const add = (category: string, items: RectificationEvent[]) => events.push(...items.map((item) => event(category, item)));
  add('family', draft.family.events);
  ([['İlkokula başlama', draft.education.primaryStart], ['Lise başlangıç', draft.education.highSchoolStart], ['Lise mezuniyet', draft.education.highSchoolGraduation], ['Üniversite başlangıç', draft.education.universityStart], ['Üniversite mezuniyet', draft.education.universityGraduation]] as const).forEach(([type, date]) => { const item = dated('education', type, date); if (item) events.push(item); });
  add('education', draft.education.events); add('relocation', draft.moves.events); add('career', draft.career.jobs); add('career', draft.career.events);
  Object.entries(draft.relationships.dates).forEach(([type, date]) => { const item = dated('relationship', type, date); if (item) events.push(item); });
  add('relationship', draft.relationships.events); add('children', draft.relationships.children);
  if (draft.relationships.includeReproductiveHealth) add('reproductive_health', draft.relationships.reproductiveEvents);
  if (draft.majorEvents.includeHealth) add('health', draft.majorEvents.healthEvents);
  if (draft.majorEvents.includeLegal) add('legal', draft.majorEvents.legalEvents);
  add('finance', draft.finance.events);
  return { request: { birth_date: draft.birth.date, birth_city: draft.birth.city.trim(), birth_district: draft.birth.district.trim() || null, birth_detail: draft.birth.detail.trim() || null, known_time_period: draft.birth.knownTimePeriod || null, known_time_start: draft.birth.knownTimeStart || null, known_time_end: draft.birth.knownTimeEnd || null, birth_method: draft.birth.method || null, birth_notes: JSON.stringify({ special_situation: draft.birth.specialSituation || null, conditions: draft.birth.birthConditions, other_condition: draft.birth.otherCondition || null }), consent: draft.consent }, events };
}
async function apiRequest(path: string, token: string, init?: RequestInit) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 20_000); try { const response = await fetch(`${ENDPOINT}${path}`, { ...init, headers: { Accept: 'application/json', Authorization: `Bearer ${token}`, ...(init?.body ? { 'Content-Type': 'application/json' } : {}) }, signal: controller.signal }); const data = await response.json().catch(() => null) as { success?: boolean; request?: { id: string; status: RectificationStatus; created_at: string; updated_at: string } | null; fields?: Record<string, string> } | null; if (response.status === 401) throw new RectificationRequestError('auth'); if (response.status === 403) throw new RectificationRequestError('entitlement'); if (response.status === 400 || response.status === 422) throw new RectificationRequestError('validation', data?.fields ?? {}); if (!response.ok || !data?.success) throw new RectificationRequestError('network'); return data as { success: true; request: { id: string; status: RectificationStatus; created_at: string; updated_at: string } | null }; } catch (error) { if (error instanceof RectificationRequestError) throw error; throw new RectificationRequestError('network'); } finally { clearTimeout(timeout); } }
export type RectificationStatus = 'draft' | 'submitted' | 'in_review' | 'completed';
export async function submitRectification(draft: RectificationDraft, token: string) { return apiRequest('', token, { method: 'POST', body: JSON.stringify(normalizeRectificationDraft(draft)) }); }
export async function getCurrentRectification(token: string) { return apiRequest('', token); }

export type PublicRectificationResult = { estimatedBirthTime: string; ascendantSign: string };
async function resultRequest(requestId: string, token: string, method: 'GET' | 'POST') {
  const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 30_000);
  try { const response = await fetch(`${ENDPOINT}/${encodeURIComponent(requestId)}/calculate`, { method, headers: { Accept: 'application/json', Authorization: `Bearer ${token}` }, signal: controller.signal }); const data = await response.json().catch(() => null) as { success?: boolean; error?: string; result?: PublicRectificationResult } | null; if (response.status === 401) throw new RectificationRequestError('auth'); if (response.status === 403) throw new RectificationRequestError('entitlement'); if (response.status === 422 && data?.error === 'insufficient_data') throw new RectificationRequestError('insufficient'); if (!response.ok || !data?.success || !data.result) throw new RectificationRequestError('network'); return data.result; } catch (error) { if (error instanceof RectificationRequestError) throw error; throw new RectificationRequestError('network'); } finally { clearTimeout(timeout); }
}
export async function calculateRectification(requestId: string, token: string) { return resultRequest(requestId, token, 'POST'); }
export async function getRectificationResult(requestId: string, token: string) { return resultRequest(requestId, token, 'GET'); }
export async function saveRectificationResult(requestId: string, token: string) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 20_000); try { const response = await fetch(`${ENDPOINT}/${encodeURIComponent(requestId)}/save`, { method: 'POST', headers: { Accept: 'application/json', Authorization: `Bearer ${token}` }, signal: controller.signal }); const data = await response.json().catch(() => null) as { error?: string; missingFields?: string[] } | null; if (response.status === 401) throw new RectificationRequestError('auth'); if (response.status === 422 && data?.error === 'profile_incomplete') throw new RectificationRequestError('profile_incomplete', {}, data.missingFields ?? []); if (!response.ok) throw new RectificationRequestError('network'); } catch (error) { if (error instanceof RectificationRequestError) throw error; throw new RectificationRequestError('network'); } finally { clearTimeout(timeout); } }
