import { StyleSheet, Text, TextInput, View } from 'react-native';
import { colors } from '@/constants/theme';
import { usePalette } from '@/localization';
import { useRectificationText } from './presentation';
import { ChoiceChips } from './FormControls';
import type { ApproximateDateValue, DatePrecision } from './types';
import { approximateDateError, formatExactDateInput } from './validation';
const choices: Array<{ value: DatePrecision; label: string }> = [{ value: 'exact', label: 'Tam tarih biliyorum' }, { value: 'month-year', label: 'Ay / yıl biliyorum' }, { value: 'year', label: 'Sadece yıl biliyorum' }, { value: 'approximate', label: 'Yaklaşık tarih' }, { value: 'unknown', label: 'Hatırlamıyorum' }, { value: 'not-applicable', label: 'Bana uygun değil / yaşamadım' }];
export function ApproximateDateInput({ label, value, onChange }: { label: string; value: ApproximateDateValue; onChange: (value: ApproximateDateValue) => void }) { const palette=usePalette(); const t=useRectificationText(); const placeholder = value.precision === 'exact' ? 'GG/AA/YYYY' : value.precision === 'month-year' ? 'AA/YYYY' : 'YYYY'; const needsInput = value.precision !== 'unknown' && value.precision !== 'not-applicable'; const error = needsInput && value.value ? approximateDateError(value) : null; const updateText = (text: string) => { const digits = text.replace(/\D/g, ''); const formatted = value.precision === 'exact' ? formatExactDateInput(text) : value.precision === 'month-year' && digits.length > 2 ? `${digits.slice(0, 2)}/${digits.slice(2, 6)}` : digits.slice(0, 4); onChange({ ...value, value: formatted }); }; return <View style={styles.group}><Text style={[styles.label,{color:palette.navy}]}>{t(label)}</Text><ChoiceChips options={choices} value={value.precision} onChange={(precision) => onChange({ precision, value: precision === 'unknown' || precision === 'not-applicable' ? '' : value.value, isApproximate: precision === 'approximate' })} />{needsInput ? <><TextInput accessibilityLabel={`${t(label)} date`} keyboardType="number-pad" maxLength={value.precision === 'exact' ? 10 : value.precision === 'month-year' ? 7 : 4} onChangeText={updateText} placeholder={placeholder} placeholderTextColor={palette.muted} style={[styles.input,{backgroundColor:palette.surface,borderColor:palette.border,color:palette.navy},error && styles.inputError]} value={value.value} />{error ? <Text accessibilityRole="alert" style={[styles.error,{color:palette.danger}]}>{t(error)}</Text> : null}</> : null}</View>; }
const styles = StyleSheet.create({ group: { gap: 9 }, label: { color: colors.navy, fontSize: 16, fontWeight: '700' }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, color: colors.navy, fontSize: 17, minHeight: 54, paddingHorizontal: 15 }, inputError: { borderColor: colors.danger }, error: { color: colors.danger, fontSize: 14 } });
