import { useCallback } from 'react';
import { useLocale } from '@/localization';
const EN:Record<string,string>={
  'DOĞUM SAATİ REKTİFİKASYONU':'BIRTH TIME RECTIFICATION','Doğum Saatini Hesaplayalım':"Let’s Calculate Your Birth Time",'Yaşamındaki önemli olayları astrolojik olarak karşılaştıran otomatik rektifikasyon çalışması.':'An automated rectification process that compares important events in your life astrologically.','Hesabın hazır':'Your account is ready','Doğum Saati Hesaplama':'Birth Time Calculation','Nasıl ilerleyecek?':'How does it work?','Rektifikasyon ürününü satın al.':'Purchase the rectification service.','Satın alma hakkın doğrulandıktan sonra 8 adımlık formu tamamla.':'After your purchase is confirmed, complete the 8-step form.','Otomatik hesaplama tamamlandığında tek doğum saatini gör ve profiline kaydet.':'When the automated calculation is complete, view the single best-matching birth time and save it to your profile.','Form, ödeme tamamlanmadan açılmaz.':'The form opens after payment is completed.','FORMA DEVAM ET':'CONTINUE FORM','8 ADIMLIK FORMA BAŞLA':'START THE 8-STEP FORM','APP STORE AÇILIYOR…':'OPENING APP STORE…',
  'Doğum Bilgilerin':'Your Birth Details','Ailedeki Önemli Dönüm Noktaları':'Important Family Milestones','Eğitim Hayatın':'Your Education','Hayatındaki Önemli Taşınmalar':'Important Moves in Your Life','Kariyer Dönüm Noktaların':'Your Career Milestones','İlişki ve Aile Zaman Çizgin':'Your Relationship and Family Timeline','Hayatındaki Büyük Kırılmalar':'Major Turning Points in Your Life','Finansal Dönüm Noktaların':'Your Financial Milestones','Zorunlu alan':'Required field','Geri':'Back','Devam Et':'Continue','Cevaplarımı Gözden Geçir':'Review My Answers','Satın alma hakkın doğrulanıyor…':'Confirming your purchase access…','Taslağın yükleniyor…':'Loading your draft…','Lütfen işaretli alanları kontrol et.':'Please check the highlighted fields.','Yaşadığın şehir veya ülke değişimlerini ve hayatındaki önemli yer değişikliklerini ekle.':'Add changes of city or country and other important moves in your life.',
  'Doğum tarihi':'Date of birth','Tarih seç':'Select date','Doğum yeri / İl':'Place of birth / City','İlçe':'District','Hastane / mahalle (opsiyonel)':'Hospital / neighborhood (optional)','Doğum saati için bildiğin aralık':'What you know about your birth time','Sabah':'Morning','Öğlen':'Noon','Akşam':'Evening','Gece':'Night','Yaklaşık saat aralığı biliyorum':'I know an approximate time range','Hiç bilmiyorum':"I don't know at all",'Başlangıç':'Start','Bitiş':'End','Doğum şekli':'Type of birth','Normal doğum':'Vaginal birth','Sezaryen':'Cesarean birth','Bilmiyorum':"I don't know",'Doğumda özel bir durum oldu mu?':'Were there any special circumstances at birth?','Hayır':'No','Evet':'Yes','Erken doğum':'Premature birth','Kuvöz':'Incubator care','Kordon dolanması':'Umbilical cord complication','Zor doğum':'Difficult birth','Acil müdahale':'Emergency intervention','Diğer':'Other','Diğer durum':'Other circumstance',
  'Tam tarih biliyorum':'I know the exact date','Ay / yıl biliyorum':'I know the month and year','Sadece yıl biliyorum':'I only know the year','Yaklaşık tarih':'Approximate date','Hatırlamıyorum':"I don't remember",'Bana uygun değil / yaşamadım':'Not applicable / I did not experience this','Kayıt':'Entry','Kaydı sil':'Delete entry','Olay türü':'Event type','Tarih':'Date','Başlangıç tarihi':'Start date','Bitiş tarihi':'End date','Devam ediyor':'Ongoing','Nereden?':'From where?','Nereye?':'To where?','Kısa açıklama (opsiyonel)':'Short description (optional)',
  'Doğum Saatin Hesaplandı':'Your Birth Time Has Been Calculated','Yükselen Burcun':'Your Rising Sign','Bu saat, verdiğin yaşam olaylarının astrolojik olarak karşılaştırılmasıyla hesaplanan en güçlü eşleşmedir.':'This is the strongest match calculated by astrologically comparing the life events you provided.','KAYDEDİLİYOR…':'SAVING…','DOĞUM SAATİMİ KAYDET':'SAVE MY BIRTH TIME','Doğum Saatin Hesaplanıyor':'Your Birth Time Is Being Calculated','Yaşam olayların aday doğum saatleriyle güvenli sunucuda astrolojik olarak karşılaştırılacak.':'Your life events will be compared astrologically with candidate birth times on a secure server.','Hesaplama tamamlandığında yalnızca en güçlü eşleşen saat ve yükselen burcun gösterilecek.':'When calculation is complete, only the strongest matching time and rising sign will be shown.','PROFİLE GİT':'GO TO PROFILE'
};
Object.assign(EN,{
  'Adım':'Step','Eğitim hayatındaki önemli değişiklikler':'Important changes in your education','İş değişiklikleri':'Job changes','Kariyerde önemli olaylar':'Important career events','İlişkiler':'Relationships','İlişkide önemli kırılmalar':'Important relationship turning points','Çocuklar':'Children','Üreme sağlığı — isteğe bağlı':'Reproductive health — optional','Bu sorular isteğe bağlıdır. Yanıtlamak istemediğin soruları boş bırakabilirsin.':'These questions are optional. You can leave any you prefer not to answer blank.','Bu bölümdeki bilgiler hassastır ve tamamen isteğe bağlıdır. Yanıtlamak istemediğin alanları boş bırakabilirsin.':'The information in this section is sensitive and entirely optional. You may leave any field blank.','Miktar belirtmen gerekmez; olayın yaklaşık tarihi rektifikasyon için yeterlidir.':'You do not need to enter an amount; an approximate date is sufficient for rectification.',
  'Bu bölümde belirgin bir olay yok':'There is no significant event in this section','Önemli taşınmam olmadı':'I have not had a significant move','Henüz çalışmadım':'I have not worked yet','Üniversiteye gitmedim':'I did not attend university','Devam ediyor / mezun olmadım':'Ongoing / I have not graduated','Sağlık, kaza veya hastane bilgisi eklemek istiyorum':'I want to add health, accident, or hospital information','Eklemek istediğim hukuki/resmi bir süreç var':'I want to add a legal or official process','Bu bilgileri eklemek istiyorum':'I want to add this information',
  '+ Olay Ekle':'+ Add Event','+ Eğitim Olayı Ekle':'+ Add Education Event','+ Taşınma Ekle':'+ Add Move','+ İş Ekle':'+ Add Job','+ Kariyer Olayı Ekle':'+ Add Career Event','+ İlişki Olayı Ekle':'+ Add Relationship Event','+ Çocuk Ekle':'+ Add Child','+ Süreç Ekle':'+ Add Process','+ Sağlık Olayı Ekle':'+ Add Health Event','+ Hukuki / Resmi Olay Ekle':'+ Add Legal / Official Event','+ Finansal Olay Ekle':'+ Add Financial Event',
  'İlkokula başlama':'Started primary school','Lise başlangıç':'Started high school','Lise mezuniyet':'High school graduation','Üniversite başlangıç':'Started university','Üniversite mezuniyet':'University graduation','İlk işe giriş tarihi':'First job date','İş / kurum':'Job / organization','Aile taşınması':'Family move','Kardeş doğumu':'Birth of a sibling','Bölüm değişimi':'Change of department','Okul değişimi':'Change of school','Eğitim':'Education','İş':'Work','Evlilik / ilişki':'Marriage / relationship','Aile':'Family','Ekonomik neden':'Financial reason','Yurtdışı':'Abroad','Terfi':'Promotion','İstifa':'Resignation','Meslek değişimi':'Career change','Ayrılık':'Separation','Boşanma':'Divorce','Barışma':'Reconciliation','Büyük ameliyat':'Major surgery','Kaza':'Accident','Dava açılışı':'Legal case opened','Mahkeme süreci':'Court process','Ev alımı':'Home purchase','Ev satışı':'Home sale','Araç alımı':'Vehicle purchase','Araç satışı':'Vehicle sale','Miras':'Inheritance'
});
Object.assign(EN,{'SON KONTROL':'FINAL CHECK','Cevaplarını Gözden Geçir':'Review Your Answers','Hesaplamayı başlatmadan önce her bölümü kontrol edebilir ve istediğin adıma dönebilirsin.':'Review each section before starting the calculation and return to any step you want.','Düzenle':'Edit','Gizlilik Politikası':'Privacy Policy','Hazırlanıyor…':'Preparing…','OTOMATİK HESAPLAMAYI BAŞLAT':'START AUTOMATED CALCULATION','Cevapların yükleniyor…':'Loading your answers…','Doğum bilgileri':'Birth details','Taşınmalar':'Moves','Kariyer':'Career','İlişki / aile':'Relationship / family','Sağlık / hukuki':'Health / legal','Finans':'Finances','Tarih yok':'No date','İl yok':'No city','Belirgin olay yok':'No significant event','Önemli taşınma yok':'No significant move'});
Object.assign(EN,{
  'Rektifikasyon çalışmasının yapılabilmesi için verdiğim bilgilerin bu amaçla işlenmesini kabul ediyorum.':'I consent to the processing of the information I provided for this rectification study.',
  'Talebini gönderebilmek için veri işleme onayını vermelisin.':'You must consent to data processing before submitting your request.',
  'Oturumunun süresi doldu. Lütfen tekrar giriş yap.':'Your session has expired. Please sign in again.',
  'Doğum saati hesaplama satın alma hakkın doğrulanamadı.':'Your Birth Time Calculation purchase could not be verified.',
  'Doğum saatini hesaplayabilmek için birkaç önemli tarih daha gerekiyor.':'A few more important dates are needed to calculate your birth time.',
  'Şu anda doğum saatini hesaplayamıyoruz. Cevapların cihazında kayıtlı; lütfen daha sonra tekrar dene.':'We cannot calculate your birth time right now. Your answers are saved on your device; please try again later.',
  'Doğum saati sonucu bulunamadı.':'Your birth time result could not be found.',
  'Doğum saati sonucu şu anda yüklenemiyor.':'Your birth time result cannot be loaded right now.',
  'Doğum saatin şu anda kaydedilemedi. Lütfen tekrar dene.':'Your birth time could not be saved right now. Please try again.',
  'Sonucun hazırlanıyor…':'Preparing your result…',
  'DOĞUM SAATİN KAYDEDİLDİ':'YOUR BIRTH TIME IS SAVED',
  'Artık Tam Doğum Haritanı Oluşturabiliriz':'Now We Can Create Your Complete Birth Chart',
  'Doğum saatin netleştiğine göre yükselen burcundan 12 evine, gezegen açılarından ilişki ve kariyer göstergelerine kadar haritanın tüm derin katmanlarını açabilirsin.':'Now that your birth time is clear, you can unlock every deeper layer of your chart, from your Rising sign and 12 houses to planetary aspects, relationships, and career indicators.',
  'Tüm Premium natal analizleri ve 12 aylık yıllık öngörü dahildir.':'Includes all Premium birth-chart analyses and your 12-month forecast.',
  'Doğum saati rektifikasyonu ve tam harita iki ayrı satın almadır.':'Birth time rectification and the complete chart are separate purchases.'
});
export function rectificationText(value:string,locale:'tr'|'en'){if(locale==='tr')return value;if(value.endsWith(', hesabın hazır'))return `${value.slice(0,-15)}, your account is ready`;const direct=EN[value];if(direct)return direct;return value.replace(/(\d+) olay/g,'$1 events').replace(/(\d+) önemli değişiklik/g,'$1 important changes').replace(/(\d+) taşınma/g,'$1 moves').replace(/(\d+) iş/g,'$1 jobs').replace(/(\d+) kariyer olayı/g,'$1 career events').replace(/(\d+) ilişki olayı/g,'$1 relationship events').replace(/(\d+) çocuk kaydı/g,'$1 child entries').replace(/(\d+) sağlık/g,'$1 health events').replace(/(\d+) hukuki kayıt/g,'$1 legal entries').replace(/(\d+) finansal olay/g,'$1 financial events');}
export function useRectificationText(){const {locale}=useLocale();return useCallback((value:string)=>rectificationText(value,locale),[locale]);}
