import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams, type Href } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, AppState, type AppStateStatus, Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { colors } from '@/constants/theme';
import { useAuth } from '@/features/auth/AuthProvider';
import { getQuestion, QuestionsApiError, type QuestionAnswer, type UserQuestion } from '@/features/questions/api';
import { questionErrorMessage, shouldPollQuestion, STATUS_LABELS } from '@/features/questions/domain';
import { createRequestGate } from '@/features/questions/requestGate';
import { useSocialNotifications } from '@/features/social/SocialNotificationProvider';

const POLL_INTERVAL_MS = 7_000;
const sections: Array<{key:keyof QuestionAnswer;title:string;icon:keyof typeof Ionicons.glyphMap}> = [
  {key:'directAnswer',title:'Kısa Cevap',icon:'sparkles-outline'}, {key:'detail',title:'Detaylı Yorum',icon:'reader-outline'}, {key:'timing',title:'Zamanlama',icon:'time-outline'}, {key:'caution',title:'Dikkat Etmen Gereken',icon:'shield-checkmark-outline'}, {key:'conclusion',title:'Sonuç',icon:'checkmark-circle-outline'},
];

export default function QuestionDetailScreen() {
  const params = useLocalSearchParams<{id?:string|string[]}>(); const id = Array.isArray(params.id) ? params.id[0] : params.id;
  const { loading: authLoading, session } = useAuth(); const { markRead, notifications } = useSocialNotifications(); const [item,setItem]=useState<UserQuestion|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [appState,setAppState]=useState<AppStateStatus>(AppState.currentState ?? 'active'); const gateRef=useRef(createRequestGate()); const markedReadRef=useRef(new Set<string>());
  const load=useCallback(async(silent=false)=>{if(!id||!session?.access_token){setLoading(false);return;}const ticket=gateRef.current.begin();if(ticket===null)return;if(!silent)setLoading(true);setError(null);try{const next=await getQuestion(session.access_token,id);if(gateRef.current.isCurrent(ticket))setItem(next);}catch(cause){if(!silent&&gateRef.current.isCurrent(ticket))setError(questionErrorMessage(cause instanceof QuestionsApiError?cause.code:undefined,cause instanceof QuestionsApiError?cause.status:undefined));}finally{if(gateRef.current.isCurrent(ticket)&&!silent)setLoading(false);gateRef.current.finish(ticket);}},[id,session?.access_token]);
  useEffect(()=>{gateRef.current.invalidate();void load();return()=>gateRef.current.invalidate();},[load]);
  useEffect(()=>()=>gateRef.current.dispose(),[]);
  useEffect(()=>{const subscription=AppState.addEventListener('change',(state)=>{if(state!=='active')gateRef.current.invalidate();else void load(false);setAppState(state);});return()=>subscription.remove();},[load]);
  useEffect(()=>{if(!item||!shouldPollQuestion(item.status,appState))return;const timer=setInterval(()=>void load(true),POLL_INTERVAL_MS);return()=>clearInterval(timer);},[appState,item?.status,load]);
  useEffect(()=>{if(!id||markedReadRef.current.has(id)||!notifications.some((notification)=>notification.type==='question_answered'&&notification.questionId===id&&!notification.read))return;markedReadRef.current.add(id);void markRead('question_answered',id);},[id,markRead,notifications]);
  if(authLoading||loading)return <Screen><View style={styles.center}><ActivityIndicator accessibilityLabel="Soru yükleniyor" color={colors.sapphire} size="large"/></View></Screen>;
  if(!session)return <Screen><State icon="person-circle-outline" title="Hesabına giriş yap" text="Bu soruyu görmek için giriş yapmalısın." action="Giriş Yap" onPress={()=>router.push('/sign-in')}/></Screen>;
  if(error||!item)return <Screen><State icon="cloud-offline-outline" title="Soru yüklenemedi" text={error??'Bu soruya şu anda ulaşılamıyor.'} action="Tekrar Dene" onPress={()=>void load()}/></Screen>;
  return <Screen><View style={styles.header}><Text style={styles.eyebrow}>SORU DETAYI</Text><Text style={styles.title}>{item.title}</Text><View style={styles.meta}><View style={[styles.badge,item.status==='answered'&&styles.readyBadge,item.status==='failed'&&styles.failedBadge]}><Text style={[styles.badgeText,item.status==='answered'&&styles.readyText,item.status==='failed'&&styles.failedText]}>{STATUS_LABELS[item.status]}</Text></View><Text style={styles.cost}>{item.starCost} ✦</Text></View></View>
    {(item.status==='queued'||item.status==='processing')?<View style={styles.preparing}><View style={styles.orbit}><ActivityIndicator color={colors.sapphire} size="large"/></View><Text style={styles.preparingTitle}>Sorun hazırlanıyor ✦</Text><Text style={styles.body}>Doğum haritan ve güncel gökyüzü hareketlerin inceleniyor. Cevabın hazır olduğunda burada görebileceksin.</Text><Text style={styles.pollHint}>Bu ekran açıkken durum otomatik yenilenir.</Text></View>:item.status==='failed'?<View style={styles.failed}><Ionicons color={colors.danger} name="refresh-circle-outline" size={38}/><Text style={styles.preparingTitle}>Bu soru tamamlanamadı</Text><Text style={styles.body}>Bu soru tamamlanamadı. Kullanılmayan Yıldızların bakiyene geri döndü.</Text><Pressable accessibilityRole="button" onPress={()=>router.push('/ask' as Href)} style={styles.button}><Text style={styles.buttonText}>Yeniden Sor</Text></Pressable></View>:<View style={styles.sections}>{sections.flatMap(({key,title,icon})=>{const content=item.answer?.[key];return content?[<View key={key} style={[styles.answerCard,key==='directAnswer'&&styles.directCard]}><View style={styles.sectionHeading}><Ionicons color={colors.sapphire} name={icon} size={22}/><Text style={styles.sectionTitle}>{title}</Text></View><Text selectable style={styles.answerText}>{content}</Text></View>]:[]})}</View>}
  </Screen>;
}
function State({action,icon,onPress,text,title}:{action:string;icon:keyof typeof Ionicons.glyphMap;onPress:()=>void;text:string;title:string}){return <View style={styles.failed}><Ionicons color={colors.sapphire} name={icon} size={38}/><Text style={styles.preparingTitle}>{title}</Text><Text style={styles.body}>{text}</Text><Pressable accessibilityRole="button" onPress={onPress} style={styles.button}><Text style={styles.buttonText}>{action}</Text></Pressable></View>}
const styles=StyleSheet.create({center:{alignItems:'center',flex:1,justifyContent:'center',minHeight:300},header:{gap:9},eyebrow:{color:colors.sapphire,fontSize:13,fontWeight:'900',letterSpacing:1.3},title:{color:colors.navy,fontSize:27,fontWeight:'900',letterSpacing:-.4,lineHeight:35},meta:{alignItems:'center',flexDirection:'row',justifyContent:'space-between',marginTop:3},badge:{backgroundColor:colors.sapphireSoft,borderRadius:12,paddingHorizontal:12,paddingVertical:7},badgeText:{color:colors.sapphire,fontSize:14,fontWeight:'900'},readyBadge:{backgroundColor:'#E7F4EC'},readyText:{color:'#266B42'},failedBadge:{backgroundColor:'#F8E8E6'},failedText:{color:colors.danger},cost:{color:colors.gold,fontSize:18,fontWeight:'900'},preparing:{alignItems:'center',backgroundColor:colors.surface,borderColor:colors.border,borderRadius:24,borderWidth:1,gap:13,padding:26},orbit:{alignItems:'center',backgroundColor:colors.sapphireSoft,borderRadius:44,height:88,justifyContent:'center',width:88},preparingTitle:{color:colors.navy,fontSize:22,fontWeight:'900',textAlign:'center'},body:{color:colors.muted,fontSize:17,lineHeight:26,textAlign:'center'},pollHint:{color:colors.muted,fontSize:13,fontWeight:'700',marginTop:4},failed:{alignItems:'center',backgroundColor:colors.surface,borderColor:colors.border,borderRadius:24,borderWidth:1,gap:12,padding:26},button:{alignItems:'center',backgroundColor:colors.sapphire,borderRadius:15,justifyContent:'center',marginTop:6,minHeight:54,paddingHorizontal:22},buttonText:{color:colors.white,fontSize:16,fontWeight:'900'},sections:{gap:14},answerCard:{backgroundColor:colors.surface,borderColor:colors.border,borderRadius:20,borderWidth:1,gap:12,padding:19},directCard:{backgroundColor:colors.sapphireSoft,borderColor:'#C7D9EE'},sectionHeading:{alignItems:'center',flexDirection:'row',gap:9},sectionTitle:{color:colors.navy,fontSize:19,fontWeight:'900'},answerText:{color:colors.navy,fontSize:17,lineHeight:27}});
