import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect, type Href } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { SectionHeader } from '@/components/SectionHeader';
import { colors } from '@/constants/theme';
import { useAuth } from '@/features/auth/AuthProvider';
import { getQuestions, QuestionsApiError, type UserQuestion } from '@/features/questions/api';
import { isVisibleQuestionStatus, questionErrorMessage, STATUS_LABELS } from '@/features/questions/domain';
import { formatDate as formatLocalizedDate, useLocale, usePalette } from '@/localization';

export default function QuestionsScreen() {
  const { locale, messages } = useLocale(); const palette = usePalette(); const q = messages.questionsList;
  const { loading: authLoading, session } = useAuth();
  const [items, setItems] = useState<UserQuestion[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const visibleItems = items.filter((item) => isVisibleQuestionStatus(item.status));
  const load = useCallback(async () => { if (authLoading) return; if (!session?.access_token) { setItems([]); setLoading(false); return; } setLoading(true); setError(null); try { setItems(await getQuestions(session.access_token)); } catch (cause) { setError(questionErrorMessage(cause instanceof QuestionsApiError ? cause.code : undefined, cause instanceof QuestionsApiError ? cause.status : undefined)); } finally { setLoading(false); } }, [authLoading, session?.access_token]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const statusLabel = (status: UserQuestion['status']) => q[status] ?? STATUS_LABELS[status];
  return <Screen><SectionHeader eyebrow={q.eyebrow} title={q.title} description={q.description} />
    {authLoading || loading ? <View style={styles.center}><ActivityIndicator accessibilityLabel={q.loading} color={palette.sapphire} size="large" /></View> : !session ? <State icon="person-circle-outline" title={q.signInTitle} text={q.signInText} action={q.signIn} onPress={() => router.push('/sign-in')} /> : error ? <State icon="cloud-offline-outline" title={q.errorTitle} text={q.errorText} action={q.retry} onPress={() => void load()} /> : !visibleItems.length ? <State icon="chatbox-ellipses-outline" title={q.emptyTitle} text={q.emptyText} action={q.ask} onPress={() => router.push('/ask' as Href)} /> : <View style={styles.list}>{visibleItems.map((item) => <Pressable accessibilityLabel={`${item.title}, ${statusLabel(item.status)}`} accessibilityRole="button" key={item.id} onPress={() => router.push(`/questions/${item.id}` as Href)} style={({pressed}) => [styles.card,{backgroundColor:palette.surface,borderColor:palette.border},pressed && styles.pressed]}><View style={styles.cardTop}><View style={styles.flex}><Text style={[styles.title,{color:palette.navy}]}>{item.title}</Text>{formatLocalizedDate(item.createdAt,locale) ? <Text style={[styles.date,{color:palette.muted}]}>{formatLocalizedDate(item.createdAt,locale)}</Text> : null}</View><Ionicons color={palette.sapphire} name="chevron-forward" size={22} /></View><View style={styles.footer}><View style={[styles.badge,{backgroundColor:palette.sapphireSoft},item.status === 'answered' && styles.readyBadge]}><Text style={[styles.badgeText,{color:palette.sapphire},item.status === 'answered' && styles.readyText]}>{statusLabel(item.status)}</Text></View><Text style={[styles.cost,{color:palette.gold}]}>{item.starCost} ✦</Text></View></Pressable>)}</View>}
  </Screen>;
}
function State({action,icon,onPress,text,title}:{action:string;icon:keyof typeof Ionicons.glyphMap;onPress:()=>void;text:string;title:string}) { const palette=usePalette(); return <View style={[styles.state,{backgroundColor:palette.surface,borderColor:palette.border}]}><Ionicons color={palette.sapphire} name={icon} size={34}/><Text style={[styles.stateTitle,{color:palette.navy}]}>{title}</Text><Text style={[styles.stateText,{color:palette.muted}]}>{text}</Text><Pressable accessibilityRole="button" onPress={onPress} style={[styles.button,{backgroundColor:palette.sapphire}]}><Text style={styles.buttonText}>{action}</Text></Pressable></View>; }
const styles=StyleSheet.create({center:{alignItems:'center',flex:1,justifyContent:'center',minHeight:260},list:{gap:12},card:{backgroundColor:colors.surface,borderColor:colors.border,borderRadius:20,borderWidth:1,gap:14,padding:18},pressed:{opacity:.7},cardTop:{alignItems:'center',flexDirection:'row',gap:10},flex:{flex:1},title:{color:colors.navy,fontSize:18,fontWeight:'800',lineHeight:25},date:{color:colors.muted,fontSize:14,marginTop:6},footer:{alignItems:'center',flexDirection:'row',justifyContent:'space-between'},badge:{backgroundColor:colors.sapphireSoft,borderRadius:12,paddingHorizontal:11,paddingVertical:7},badgeText:{color:colors.sapphire,fontSize:13,fontWeight:'900'},readyBadge:{backgroundColor:'#E7F4EC'},readyText:{color:'#266B42'},failedBadge:{backgroundColor:'#F8E8E6'},failedText:{color:colors.danger},cost:{color:colors.gold,fontSize:16,fontWeight:'900'},state:{alignItems:'center',backgroundColor:colors.surface,borderColor:colors.border,borderRadius:22,borderWidth:1,gap:10,padding:24},stateTitle:{color:colors.navy,fontSize:21,fontWeight:'900',textAlign:'center'},stateText:{color:colors.muted,fontSize:16,lineHeight:24,textAlign:'center'},button:{alignItems:'center',backgroundColor:colors.sapphire,borderRadius:15,justifyContent:'center',marginTop:6,minHeight:54,paddingHorizontal:22},buttonText:{color:colors.white,fontSize:16,fontWeight:'900'}});
