import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect, type Href } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { SectionHeader } from '@/components/SectionHeader';
import { colors } from '@/constants/theme';
import { useAuth } from '@/features/auth/AuthProvider';
import { getQuestions, QuestionsApiError, type UserQuestion } from '@/features/questions/api';
import { isVisibleQuestionStatus, questionErrorMessage, STATUS_LABELS } from '@/features/questions/domain';

function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : new Intl.DateTimeFormat('tr-TR', { day:'numeric', month:'long', year:'numeric' }).format(date); }

export default function QuestionsScreen() {
  const { loading: authLoading, session } = useAuth();
  const [items, setItems] = useState<UserQuestion[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const visibleItems = items.filter((item) => isVisibleQuestionStatus(item.status));
  const load = useCallback(async () => { if (authLoading) return; if (!session?.access_token) { setItems([]); setLoading(false); return; } setLoading(true); setError(null); try { setItems(await getQuestions(session.access_token)); } catch (cause) { setError(questionErrorMessage(cause instanceof QuestionsApiError ? cause.code : undefined, cause instanceof QuestionsApiError ? cause.status : undefined)); } finally { setLoading(false); } }, [authLoading, session?.access_token]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  return <Screen><SectionHeader eyebrow="SORULARIM" title="Sorularım" description="Gönderdiğin soruları ve hazır yorumlarını buradan takip et." />
    {authLoading || loading ? <View style={styles.center}><ActivityIndicator accessibilityLabel="Sorular yükleniyor" color={colors.sapphire} size="large" /></View> : !session ? <State icon="person-circle-outline" title="Hesabına giriş yap" text="Sorularını görmek için giriş yapmalısın." action="Giriş Yap" onPress={() => router.push('/sign-in')} /> : error ? <State icon="cloud-offline-outline" title="Soruların yüklenemedi" text={error} action="Tekrar Dene" onPress={() => void load()} /> : !visibleItems.length ? <State icon="chatbox-ellipses-outline" title="Henüz takip ettiğin bir sorun yok" text="Hazır sorulardan birini seçebilir veya kendi sorunu yazabilirsin." action="Safir’e Sor" onPress={() => router.push('/ask' as Href)} /> : <View style={styles.list}>{visibleItems.map((item) => <Pressable accessibilityLabel={`${item.title}, ${STATUS_LABELS[item.status]}`} accessibilityRole="button" key={item.id} onPress={() => router.push(`/questions/${item.id}` as Href)} style={({pressed}) => [styles.card, pressed && styles.pressed]}><View style={styles.cardTop}><View style={styles.flex}><Text style={styles.title}>{item.title}</Text>{formatDate(item.createdAt) ? <Text style={styles.date}>{formatDate(item.createdAt)}</Text> : null}</View><Ionicons color={colors.sapphire} name="chevron-forward" size={22} /></View><View style={styles.footer}><View style={[styles.badge, item.status === 'answered' && styles.readyBadge]}><Text style={[styles.badgeText, item.status === 'answered' && styles.readyText]}>{STATUS_LABELS[item.status]}</Text></View><Text style={styles.cost}>{item.starCost} ✦</Text></View></Pressable>)}</View>}
  </Screen>;
}
function State({action,icon,onPress,text,title}:{action:string;icon:keyof typeof Ionicons.glyphMap;onPress:()=>void;text:string;title:string}) { return <View style={styles.state}><Ionicons color={colors.sapphire} name={icon} size={34}/><Text style={styles.stateTitle}>{title}</Text><Text style={styles.stateText}>{text}</Text><Pressable accessibilityRole="button" onPress={onPress} style={styles.button}><Text style={styles.buttonText}>{action}</Text></Pressable></View>; }
const styles=StyleSheet.create({center:{alignItems:'center',flex:1,justifyContent:'center',minHeight:260},list:{gap:12},card:{backgroundColor:colors.surface,borderColor:colors.border,borderRadius:20,borderWidth:1,gap:14,padding:18},pressed:{opacity:.7},cardTop:{alignItems:'center',flexDirection:'row',gap:10},flex:{flex:1},title:{color:colors.navy,fontSize:18,fontWeight:'800',lineHeight:25},date:{color:colors.muted,fontSize:14,marginTop:6},footer:{alignItems:'center',flexDirection:'row',justifyContent:'space-between'},badge:{backgroundColor:colors.sapphireSoft,borderRadius:12,paddingHorizontal:11,paddingVertical:7},badgeText:{color:colors.sapphire,fontSize:13,fontWeight:'900'},readyBadge:{backgroundColor:'#E7F4EC'},readyText:{color:'#266B42'},failedBadge:{backgroundColor:'#F8E8E6'},failedText:{color:colors.danger},cost:{color:colors.gold,fontSize:16,fontWeight:'900'},state:{alignItems:'center',backgroundColor:colors.surface,borderColor:colors.border,borderRadius:22,borderWidth:1,gap:10,padding:24},stateTitle:{color:colors.navy,fontSize:21,fontWeight:'900',textAlign:'center'},stateText:{color:colors.muted,fontSize:16,lineHeight:24,textAlign:'center'},button:{alignItems:'center',backgroundColor:colors.sapphire,borderRadius:15,justifyContent:'center',marginTop:6,minHeight:54,paddingHorizontal:22},buttonText:{color:colors.white,fontSize:16,fontWeight:'900'}});
