import Ionicons from '@expo/vector-icons/Ionicons';
import { router,useLocalSearchParams } from 'expo-router';
import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Linking,Pressable,StyleSheet,Text,View } from 'react-native';
import { Screen } from '@/components/Screen';
import { fetchLegalDocument,isLegalDocumentId,LEGAL_DOCUMENTS,type LegalDocumentId } from '@/features/legal/documents';
import { useLocale,usePalette } from '@/localization';
export default function LegalDocumentScreen(){const params=useLocalSearchParams<{document?:string|string[]}>();const raw=Array.isArray(params.document)?params.document[0]:params.document;const id:LegalDocumentId=isLegalDocumentId(raw)?raw:'privacy';const {locale,messages}=useLocale();const palette=usePalette();const m=messages.legal;const [content,setContent]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const load=useCallback(async()=>{setLoading(true);setError(false);try{setContent(await fetchLegalDocument(id));}catch{setError(true);}finally{setLoading(false);}},[id]);useEffect(()=>{void load();},[load]);const title=id==='privacy'?m.privacy:id==='terms'?m.terms:m.kvkk;return <Screen bottomPadding={32}><View style={styles.header}><Pressable accessibilityLabel={m.back} accessibilityRole="button" onPress={()=>router.back()} style={[styles.back,{backgroundColor:palette.surface,borderColor:palette.border}]}><Ionicons name="chevron-back" size={23} color={palette.navy}/></Pressable><Text style={[styles.title,{color:palette.navy}]}>{title}</Text></View>{locale==='en'?<Text style={[styles.notice,{backgroundColor:palette.sapphireSoft,color:palette.muted}]}>{m.canonicalNotice}</Text>:null}{loading?<View style={styles.state}><ActivityIndicator color={palette.sapphire}/><Text style={[styles.stateText,{color:palette.muted}]}>{m.loading}</Text></View>:error?<View style={[styles.error,{backgroundColor:palette.surface,borderColor:palette.border}]}><Text style={[styles.errorTitle,{color:palette.navy}]}>{m.error}</Text><Pressable accessibilityRole="button" onPress={()=>void load()} style={[styles.primary,{backgroundColor:palette.sapphire}]}><Text style={styles.primaryText}>{m.retry}</Text></Pressable></View>:<Text selectable style={[styles.content,{color:palette.navy}]}>{content}</Text>}<Pressable accessibilityRole="link" onPress={()=>void Linking.openURL(LEGAL_DOCUMENTS[id].url)} style={styles.web}><Text style={[styles.webText,{color:palette.sapphire}]}>{m.web}</Text><Ionicons name="open-outline" size={17} color={palette.sapphire}/></Pressable></Screen>;}
const styles=StyleSheet.create({header:{alignItems:'center',flexDirection:'row',gap:12,minHeight:48},back:{alignItems:'center',borderRadius:18,borderWidth:1,height:40,justifyContent:'center',width:40},title:{flex:1,fontSize:24,fontWeight:'900',lineHeight:30},notice:{borderRadius:12,fontSize:13,lineHeight:19,padding:12},content:{fontSize:16,lineHeight:25},state:{alignItems:'center',gap:10,justifyContent:'center',minHeight:220},stateText:{fontSize:15},error:{alignItems:'center',borderRadius:18,borderWidth:1,gap:14,padding:20},errorTitle:{fontSize:16,lineHeight:23,textAlign:'center'},primary:{alignItems:'center',borderRadius:14,justifyContent:'center',minHeight:48,paddingHorizontal:22},primaryText:{color:'#FFFFFF',fontSize:15,fontWeight:'800'},web:{alignItems:'center',alignSelf:'center',flexDirection:'row',gap:6,minHeight:48,paddingHorizontal:12},webText:{fontSize:15,fontWeight:'800'}});
