import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { colors } from '@/constants/theme';
import { useAstrologyChart } from '@/features/astrology/AstrologyChartProvider';
import { getAnnualForecast, type AnnualForecast, type ForecastMonth, type ForecastQuestion } from '@/features/astrology/api/annual-forecast';
import { useAuth } from '@/features/auth/AuthProvider';
import { useEntitlements } from '@/features/premium/EntitlementProvider';
import { createAnnualQuestionPresentation, createMonthlyForecastPresentation } from '@/features/premium/annualForecastPresentation';

export default function AnnualForecastScreen() { const { request } = useAstrologyChart(); const { session } = useAuth(); const { hasEntitlement, loading } = useEntitlements(); const [forecast, setForecast] = useState<AnnualForecast | null>(null); const [error, setError] = useState(''); const allowed = hasEntitlement('annual_forecast'); useEffect(() => { if (!loading && allowed && request && session?.access_token) void getAnnualForecast(request, session.access_token).then((result) => setForecast(result.forecast)).catch(() => setError('12 aylık öngörün şu anda yüklenemiyor. Lütfen biraz sonra tekrar dene.')); }, [allowed, loading, request, session?.access_token]); if (loading) return <Screen><ActivityIndicator color={colors.sapphire} /></Screen>; if (!allowed) return <Screen><View style={styles.center}><Ionicons name="lock-closed" size={32} color={colors.gold} /><Text style={styles.title}>Önündeki 12 Ay</Text><Text style={styles.text}>Bu içerik 12 Aylık Yıllık Öngörü veya Tüm Haritamı Aç paketine dahildir.</Text><Pressable onPress={() => router.replace('/premium')} style={styles.cta}><Text style={styles.ctaText}>12 AYLIK ÖNGÖRÜMÜ AÇ</Text></Pressable></View></Screen>; if (!request) return <Screen><View style={styles.center}><Text style={styles.title}>Önce haritanı oluştur</Text><Pressable onPress={() => router.replace('/birth-chart')} style={styles.cta}><Text style={styles.ctaText}>DOĞUM BİLGİLERİNE GİT</Text></Pressable></View></Screen>; if (error) return <Screen><Text style={styles.error}>{error}</Text></Screen>; if (!forecast) return <Screen><View style={styles.center}><ActivityIndicator color={colors.sapphire} /><Text style={styles.text}>Gerçek transitlerin hesaplanıyor…</Text></View></Screen>; return <Screen><AnnualForecastExperience forecast={forecast} /></Screen>; }
export function AnnualForecastExperience({ forecast, preview = false }: { forecast: AnnualForecast; preview?: boolean }) { const questions = useMemo(() => createAnnualQuestionPresentation(forecast), [forecast]); const months = useMemo(() => createMonthlyForecastPresentation(forecast), [forecast]); return <><View style={styles.header}>{preview ? <Text style={styles.previewBadge}>DEVELOPMENT PREVIEW</Text> : null}<Text style={styles.eyebrow}>KİŞİSEL YILLIK ÖNGÖRÜ</Text><Text style={styles.title}>Önündeki 12 Ay</Text><Text style={styles.text}>Natal haritan ve gerçek gezegen transitleri karşılaştırılarak hazırlanmıştır.</Text></View><View style={styles.summary}><Summary label="En güçlü aşk dönemi" value={forecast.summary.love} /><Summary label="En güçlü kariyer dönemi" value={forecast.summary.career} /><Summary label="Maddi açıdan dikkat çeken dönem" value={forecast.summary.money} /><Summary label="En önemli değişim dönemi" value={forecast.summary.change} /></View><View style={styles.months}>{questions.map((question) => <QuestionCard key={question.id} question={question} />)}</View><View style={styles.months}>{months.map((month) => <MonthCard key={month.id} month={month} />)}</View></>; }
function Summary({ label, value }: { label: string; value: string }) { return <View style={styles.summaryRow}><Text style={styles.summaryLabel}>{label}</Text><Text style={styles.summaryValue}>{value}</Text></View>; }
function QuestionCard({ question }: { question: ForecastQuestion }) { const [open, setOpen] = useState(false); return <View style={styles.card}><Text style={styles.month}>{question.title}</Text>{question.period ? <Text style={styles.summaryValue}>Öne Çıkan Dönem · {question.period}</Text> : null}<Pressable onPress={() => setOpen((value) => !value)} style={styles.detailButton}><Text style={styles.detailButtonText}>{open ? 'Detayı Gizle' : 'Yanıtı Gör'}</Text><Ionicons name={open ? 'chevron-up' : 'chevron-down'} size={18} color={colors.sapphire} /></Pressable>{open ? <View style={styles.details}><Text style={styles.text}>{question.answer}</Text>{question.indicators.length ? <View style={styles.section}><Text style={styles.sectionTitle}>Bu yorumu etkileyen transitler</Text>{question.indicators.map((item) => <Text key={item} style={styles.date}>{item}</Text>)}</View> : null}</View> : null}</View>; }
function MonthCard({ month }: { month: ForecastMonth }) { const [open, setOpen] = useState(false); return <View style={styles.card}><Text style={styles.month}>{month.label}</Text><Text style={styles.theme}>{month.mainTheme}</Text><Pressable onPress={() => setOpen((value) => !value)} style={styles.detailButton}><Text style={styles.detailButtonText}>{open ? 'Detayı Gizle' : 'Detayı Gör'}</Text><Ionicons name={open ? 'chevron-up' : 'chevron-down'} size={18} color={colors.sapphire} /></Pressable>{open ? <View style={styles.details}>{month.sections.map((section) => <View key={section.id} style={styles.section}><Text style={styles.sectionTitle}>{section.title}</Text><Text style={styles.text}>{section.text}</Text></View>)}{month.opportunity ? <View style={styles.callout}><Text style={styles.opportunity}>Fırsat</Text><Text style={styles.text}>{month.opportunity}</Text></View> : null}{month.attention ? <View style={styles.callout}><Text style={styles.attention}>Dikkat Et</Text><Text style={styles.text}>{month.attention}</Text></View> : null}{month.importantDates.length ? <View style={styles.section}><Text style={styles.sectionTitle}>Öne Çıkan Tarihler</Text>{month.importantDates.map((item) => <Text key={`${item.date}-${item.title}`} style={styles.date}>{new Date(`${item.date}T12:00:00Z`).toLocaleDateString('tr-TR', { day: 'numeric', month: 'long' })} — {item.title}</Text>)}</View> : null}</View> : null}</View>; }
const styles = StyleSheet.create({ header: { alignItems: 'center', gap: 8 }, previewBadge: { backgroundColor: colors.gold, borderRadius: 99, color: colors.white, fontSize: 10, fontWeight: '900', letterSpacing: 0.8, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 5 }, eyebrow: { color: colors.sapphire, fontSize: 12, fontWeight: '900', letterSpacing: 1 }, title: { color: colors.navy, fontSize: 30, fontWeight: '900', textAlign: 'center' }, text: { color: colors.muted, fontSize: 15, lineHeight: 22 }, summary: { backgroundColor: colors.surface, borderColor: colors.gold, borderRadius: 20, borderWidth: 1, padding: 15 }, summaryRow: { borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, gap: 3, paddingVertical: 9 }, summaryLabel: { color: colors.muted, fontSize: 13 }, summaryValue: { color: colors.navy, fontSize: 16, fontWeight: '900' }, months: { gap: 10 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 18, borderWidth: 1, gap: 7, padding: 14 }, month: { color: colors.navy, fontSize: 20, fontWeight: '900', textTransform: 'capitalize' }, theme: { color: colors.muted, fontSize: 15, lineHeight: 21 }, detailButton: { alignItems: 'center', flexDirection: 'row', gap: 5, minHeight: 44 }, detailButtonText: { color: colors.sapphire, fontSize: 14, fontWeight: '900' }, details: { gap: 13 }, section: { gap: 5 }, sectionTitle: { color: colors.navy, fontSize: 16, fontWeight: '900' }, callout: { backgroundColor: colors.sapphireSoft, borderRadius: 13, gap: 5, padding: 11 }, opportunity: { color: colors.sapphire, fontSize: 14, fontWeight: '900' }, attention: { color: colors.gold, fontSize: 14, fontWeight: '900' }, date: { color: colors.navy, fontSize: 14, lineHeight: 20 }, center: { alignItems: 'center', gap: 16, paddingTop: 70 }, cta: { alignItems: 'center', alignSelf: 'stretch', backgroundColor: colors.sapphire, borderRadius: 16, justifyContent: 'center', minHeight: 56 }, ctaText: { color: colors.white, fontSize: 16, fontWeight: '900' }, error: { backgroundColor: '#F8E8E8', borderRadius: 14, color: colors.danger, fontSize: 15, lineHeight: 22, padding: 14 } });
