import Ionicons from '@expo/vector-icons/Ionicons';
import { Linking, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { colors, darkColors } from '@/constants/theme';
import { useLocale, type ActiveLocale, type ThemePreference } from '@/localization';

const themes: ThemePreference[] = ['system', 'light', 'dark']; const locales: ActiveLocale[] = ['tr', 'en'];
export default function SettingsScreen() { const l=useLocale(); const c=l.colorScheme==='dark'?darkColors:colors; const m=l.messages.settings; return <Screen><Text style={[styles.title,{color:c.navy}]}>{m.title}</Text><Section title={m.appearance} c={c}>{themes.map(v=><Choice key={v} label={m[v]} selected={l.theme===v} onPress={()=>void l.setTheme(v).catch(()=>undefined)} c={c}/>)}</Section><Section title={m.language} c={c}>{locales.map(v=><Choice key={v} label={v==='tr'?m.turkish:m.english} selected={l.locale===v} onPress={()=>void l.setLocale(v).catch(()=>undefined)} c={c}/>)}</Section><Section title={m.privacy} c={c}><View style={styles.row}><Text style={[styles.text,{color:c.navy}]}>{m.hideLastName}</Text><Switch accessibilityLabel={m.hideLastName} value={l.hideLastName} onValueChange={v=>void l.setHideLastName(v).catch(()=>undefined)}/></View></Section><Section title={m.account} c={c}><Text style={[styles.disabled,{color:c.muted}]}>{m.suspended}</Text><Text style={[styles.disabled,{color:c.muted}]}>{m.delete}</Text></Section><Section title={m.legal} c={c}>{[['https://safircan.com/gizlilik',m.privacyPolicy],['https://safircan.com/kullanim-kosullari',m.terms],['https://safircan.com/aydinlatma-metni',m.kvkk]].map(([url,label])=><Pressable accessibilityRole="link" key={url} onPress={()=>void Linking.openURL(url)} style={styles.row}><Text style={[styles.link,{color:c.sapphire}]}>{label}</Text><Ionicons name="open-outline" size={18} color={c.sapphire}/></Pressable>)}</Section></Screen> }
function Section({title,children,c}:{title:string;children:React.ReactNode;c:typeof colors|typeof darkColors}) { return <View style={[styles.section,{backgroundColor:c.surface,borderColor:c.border}]}><Text style={[styles.heading,{color:c.navy}]}>{title}</Text>{children}</View> }
function Choice({label,selected,onPress,c}:{label:string;selected:boolean;onPress:()=>void;c:typeof colors|typeof darkColors}) { return <Pressable accessibilityRole="radio" accessibilityState={{checked:selected}} onPress={onPress} style={styles.row}><Text style={[styles.text,{color:c.navy}]}>{label}</Text><Ionicons name={selected?'radio-button-on':'radio-button-off'} size={22} color={c.sapphire}/></Pressable> }
const styles=StyleSheet.create({title:{fontSize:30,fontWeight:'900'},section:{borderRadius:18,borderWidth:1,gap:5,padding:16},heading:{fontSize:18,fontWeight:'900',marginBottom:5},row:{alignItems:'center',flexDirection:'row',justifyContent:'space-between',minHeight:48},text:{fontSize:16},disabled:{fontSize:15,lineHeight:22,paddingVertical:8},link:{fontSize:16,fontWeight:'700'}});
