import type { PremiumNatalResponse, PremiumReportAnalysis, PremiumReportIndicator } from '@/features/astrology/api/types';

type PremiumData = PremiumNatalResponse['premium'];
const fire = new Set(['Koç', 'Aslan', 'Yay', 'Aries', 'Leo', 'Sagittarius']);
const water = new Set(['Yengeç', 'Akrep', 'Balık', 'Cancer', 'Scorpio', 'Pisces']);
const earth = new Set(['Boğa', 'Başak', 'Oğlak', 'Taurus', 'Virgo', 'Capricorn']);
const air = new Set(['İkizler', 'Terazi', 'Kova', 'Gemini', 'Libra', 'Aquarius']);
const tr: Record<string, string> = { Aries: 'Koç', Taurus: 'Boğa', Gemini: 'İkizler', Cancer: 'Yengeç', Leo: 'Aslan', Virgo: 'Başak', Libra: 'Terazi', Scorpio: 'Akrep', Sagittarius: 'Yay', Capricorn: 'Oğlak', Aquarius: 'Kova', Pisces: 'Balık' };

function point(data: PremiumData, id: string) { return data.report.indicators.find((item) => item.id === id); }
function house(item: PremiumReportIndicator | undefined, ...ids: number[]) { return item?.house ? ids.includes(item.house) : false; }
function title(data: PremiumData, id: string) { return point(data, id)?.title.replace(/ — \d+°\d+'$/, '') ?? ''; }
function angle(data: PremiumData, id: 'asc' | 'dsc' | 'mc') { const item = data.wheel.angles[id]; return `${id.toUpperCase()} — ${tr[item.sign] ?? item.sign}`; }
function houseChip(data: PremiumData, id: number) { const item = data.wheel.houses.find((value) => value.id === id); return `${id}. Ev — ${tr[item?.sign ?? ''] ?? item?.sign ?? ''}`; }
function chips(data: PremiumData, ids: string[], extras: string[] = []) { return [...extras, ...ids.map((id) => title(data, id)).filter(Boolean)].slice(0, 5); }

export function createNatalQuestionAnswers(data: PremiumData): PremiumReportAnalysis[] {
  const sun = point(data, 'sun'), moon = point(data, 'moon'), mercury = point(data, 'mercury'), venus = point(data, 'venus'), mars = point(data, 'mars');
  const saturn = point(data, 'saturn'), jupiter = point(data, 'jupiter'), pluto = point(data, 'pluto'), chiron = point(data, 'chiron'), north = point(data, 'north-node');
  const steady = earth.has(sun?.sign ?? '') || earth.has(saturn?.sign ?? '') || data.distributions.dominantModality === 'Sabit';
  const deep = water.has(moon?.sign ?? '') || house(moon, 4, 8, 12) || house(pluto, 1, 8, 12);
  const visible = fire.has(sun?.sign ?? '') || house(sun, 1, 5, 10);
  const cerebral = air.has(mercury?.sign ?? '') || house(mercury, 3, 9, 11);
  const independent = air.has(mars?.sign ?? '') || house(mars, 1, 9, 10, 11);
  const relational = house(venus, 7, 8) || house(moon, 7, 8) || water.has(venus?.sign ?? '');
  const disciplined = steady || house(saturn, 1, 6, 10);
  const entrepreneurial = independent && (fire.has(jupiter?.sign ?? '') || house(jupiter, 1, 10, 11));
  const hard = data.wheel.aspects.filter((item) => /square|opposition|kare|karşıt/i.test(item.type)).length >= 2;
  const sensitive = Boolean(chiron) && (house(chiron, 1, 4, 7, 8, 12) || water.has(chiron?.sign ?? ''));
  const closures = [
    'Kendini en doğru, güçlü görünmeye çalışmadığın; sezgini, aklını ve kararlılığını aynı amaç için kullandığın zaman ifade ediyorsun.',
    'İlk izlenimin güçlü olsa da seni gerçekten tanımlayan taraf, güven oluştuğunda gösterdiğin sadakat, derinlik ve istikrarlı ilgidir.',
    'Kendine düzenli bir iç alan açtığında duyguların seni yönetmek yerine neye ihtiyaç duyduğunu gösteren güvenilir bir pusulaya dönüşür.',
    'Dengeyi koruduğunda cesaretin, sezgin ve dayanıklılığın birlikte çalışır; böylece gölge yanların kararlarını yönetmeden gerçek gücün görünür olur.',
    'Uzun vadede seni mutlu eden ilişki, çekimin yanında arkadaşlık, açık iletişim, karşılıklı saygı ve güvenilir davranışlar da taşıyan ilişkidir.',
    'Yeni bir ilişkide yalnız hissettiğin çekime değil, kişinin zor anlarda nasıl davrandığına bakman sana daha sağlıklı bir seçim alanı açar.',
    'Kalıcı birliktelik potansiyelin, iki tarafın da sınırlarını koruduğu ve geleceği günlük emekle birlikte kurduğu ilişkilerde daha rahat açılır.',
    'Dersini öğrendiğinde sevgi uğruna kendini küçültmez, özgürlük uğruna da yakınlıktan vazgeçmezsin; ikisini aynı ilişkide taşıyabilirsin.',
    'Meslek seçerken yalnız unvana değil, gün içinde hangi sorunları çözeceğine ve ne kadar karar alanına sahip olacağına bakman daha doğru olur.',
    'Bugün için en verimli yol, deneyim ve çevre kazandıran bir yapıda güçlenirken gelecekteki bağımsız çalışma ihtimalini bilinçli biçimde hazırlamak.',
    'Gelirini artıran temel unsur daha çok çalışmak değil, uzmanlığını görünür, ölçülebilir ve başkalarının ödeme yapmak isteyeceği bir değere dönüştürmek.',
    'Servet açısından en güçlü yaklaşımın, kazancı çeşitlendirirken borç ve ortak para konularında şeffaf kalmak ve büyümeyi zamana yaymaktır.',
    'Bu dersi benimsediğinde başkalarının çizdiği güvenli sınırlar içinde kalmak yerine, disiplinini sana gerçekten ait bir yaşam kurmak için kullanırsın.',
    'Gelişim, bildiğin becerileri terk etmekten değil; onları kişisel cesaretin, yaratıcılığın ve görünür olma isteğin için kullanmaktan geçiyor.',
    'Sembolik geçmişin sana güçlü bir gözlem yeteneği bırakmış olabilir; şimdi bu yeteneği kendi hayatının merkezinde daha bilinçli kullanman gerekiyor.',
    'Erken fark ettiğin her gerilim, sonradan büyüyecek bir çatışmayı önleme fırsatıdır; düzenli sınırlar ve açık iletişim burada en güçlü desteğindir.',
    'Stresi ilk aşamada fark edip yükünü paylaşman, günlük düzenini sadeleştirmen ve duygularına isim vermen hassas alanlarını korumana yardımcı olur.',
  ];
  const make = (id: number, titleText: string, text: string, indicators: string[]): PremiumReportAnalysis => ({ id: `natal-question-${id}`, title: titleText, text: `${text} ${closures[id - 1]}`, indicators });

  return [
    make(1, 'Gerçek karakterim ne?', `Sen ${steady ? 'dayanıklı, sorumluluk alan ve başladığı işi sonuçlandırmak isteyen' : 'meraklı, değişime açık ve yeni yollar denemekten çekinmeyen'} birisin. ${deep ? 'İnsanları yüzeyden okumaz, söylenmeyen duyguları ve gizli niyetleri hızla sezersin.' : 'Olayları akıl süzgecinden geçirir, işe yarayan bağlantıları kısa sürede fark edersin.'} ${visible ? 'Doğru hedefi bulduğunda dikkat çeken, güven veren ve yön gösteren bir ağırlık oluşturursun.' : 'Gücünü gösterişten çok tutarlılığın ve davranışlarının kalitesiyle belli edersin.'} İnsanlar sende, baskı arttığında bile çözüm arayan ve kolay vazgeçmeyen bir taraf görebilir. Zorlandığında içine kapanmak yerine neyi kontrol edebileceğini belirlemek seni yeniden toparlar.`, chips(data, ['sun', 'moon', 'mercury', 'saturn'], [angle(data, 'asc')])),
    make(2, 'Dışarıdan nasıl görünüyorum?', `İlk tanışmada ${visible ? 'kendinden emin, doğrudan ve ne istediğini bilen' : 'ölçülü, dikkatli ve kolay açılmayan'} biri gibi görünüyorsun. İnsanlar sende ${disciplined ? 'ciddiyet, güvenilirlik ve sorumluluk duygusunu' : 'hareketlilik, merak ve hızlı uyum yeteneğini'} erken fark edebilir. İçeride daha yoğun duygular yaşasan bile dışarıya çoğu zaman kontrollü bir duruş veriyorsun. Kendi alanına saygı gösterildiğinde sıcak, koruyucu ve daha ulaşılabilir olman kolaylaşıyor. Seni uzaktan soğuk sananlar, yakından tanıdıkça mizahını ve sadakatini daha net görebilir.`, chips(data, ['sun', 'mars', 'saturn'], [angle(data, 'asc'), houseChip(data, 1)])),
    make(3, 'İç dünyam neden bu kadar farklı?', `Dışarıdan ${visible ? 'güçlü ve kontrollü' : 'sakin ve akılcı'} görünürken içeride çok daha fazla ayrıntıyı aynı anda hissediyorsun. ${deep ? 'Duyguların kolay geçmiyor; güven, sadakat ve kaybetme ihtimali üzerinde uzun süre düşünebiliyorsun.' : 'Duygularını hemen göstermek yerine önce anlamlandırmaya ve mantıklı bir yere oturtmaya çalışıyorsun.'} Bu yüzden çevren senin ne kadar etkilendiğini her zaman fark etmeyebilir. Yalnız kalma ihtiyacını suçluluk duymadan karşılamak ve hislerini biriktirmeden paylaşmak, iç dünya ile dış duruş arasındaki mesafeyi azaltır.`, chips(data, ['moon', 'sun', 'pluto'], [houseChip(data, 4), houseChip(data, 12)])),
    make(4, 'Hangi özelliklerim güçlü, hangileri gölge tarafım?', `Güçlü yanların ${steady ? 'dayanıklılık, sorumluluk ve uzun vadeli düşünme' : 'esneklik, merak ve hızlı çözüm üretme'}; ayrıca ${deep ? 'insanların niyetini sezmekte ve krizlerde soğukkanlı kalmakta' : 'bilgiyi düzenlemekte ve seçenekleri karşılaştırmakta'} başarılısın. Bir hedefe gerçekten inandığında mücadeleyi kolay bırakmıyorsun. Gölge tarafta ise ${hard ? 'kontrolü kaybetme korkusu, katılaşma ve her yükü tek başına taşıma eğilimi' : 'sabırsızlık, dağılma ve zor duyguları erteleme eğilimi'} öne çıkabilir. Duygularını zamanında ifade etmek, güçlü ve hassas tarafların arasında sağlıklı bir denge kurmana yardım eder. Gücünü kanıtlamaya çalışmak yerine gerektiğinde destek istemen, kapasiteni çok daha dengeli kullanmanı sağlar.`, chips(data, ['sun', 'moon', 'mars', 'saturn', 'pluto'])),
    make(5, 'Nasıl bir eşle mutlu olurum?', `Sen ${relational ? 'duygusal olarak derin, sadakati önemseyen ve yakınlıktan kaçmayan' : 'dürüst, zihinsel olarak canlı ve kişisel alana saygılı'} biriyle daha mutlu olursun. Karşındaki kişinin sözünün arkasında durması, gelecek konusunda sorumluluk alması ve sorunları sessizlikle cezalandırmak yerine konuşabilmesi önemli. ${independent ? 'İlişkide nefes alabileceğin bir alan isterken güçlü çekim ve ortak heyecan da arıyorsun.' : 'Güven oluştuğunda düzenli ilgi, sıcaklık ve birlikte karar vermek seni ilişkiye bağlar.'} Sana uygun eş, seni yönetmeye çalışmadan hedeflerini destekleyen ve duygusal yakınlığı günlük davranışlarıyla gösteren kişidir.`, chips(data, ['venus', 'mars', 'moon', 'juno'], [angle(data, 'dsc')])),
    make(6, 'Neden hep aynı tip insanı çekiyorum?', `Hayatına sık sık ${relational ? 'güçlü duyguları olan, çekici fakat kendi karmaşasını da ilişkiye taşıyan' : 'bağımsız, mesafeli veya kolay tanımlanamayan'} kişiler girebilir. Çünkü sen hem güven ve bağlılık arıyor hem de sıradanlaşmayan bir çekim hissetmek istiyorsun. Bu ikili ihtiyaç, başlangıçta heyecan veren fakat zamanla sınır ve açıklık sorunu yaratan ilişkileri tekrarlatabilir. Tanıdık gelen yoğunluğu gerçek uyum sanmadan önce kişinin tutarlılığına, iletişim biçimine ve sorumluluk alıp almadığına bakman döngüyü değiştirir.`, chips(data, ['venus', 'mars', 'moon', 'juno', 'south-node'])),
    make(7, 'Evlilik potansiyelim var mı?', `Haritanda uzun süreli birliktelik kurma isteği ve bunu sürdürebilecek ciddiyet bulunuyor. ${disciplined ? 'Bağlandığında sorumluluk alır, ilişkinin geleceği için emek vermekten kaçınmazsın.' : 'İlişkinin canlı kalması, karşılıklı gelişim ve açık iletişim senin için özellikle belirleyicidir.'} Ancak evlilik yalnız yoğun çekimle değil, güvenilir davranışlar ve ortak hedeflerle güçlenir. ${hard ? 'Yakınlık arttığında kontrol, mesafe veya beklenti sorunlarını açıkça konuşmak ilişkinin dayanıklılığını belirler.' : 'Duygularını saklamadan paylaşman ortak yaşamı daha sıcak ve sürdürülebilir kılar.'} Burada zaman değil, doğru kişiyle kurabileceğin ilişkinin niteliği anlatılıyor.`, chips(data, ['juno', 'venus', 'saturn', 'moon'], [angle(data, 'dsc')])),
    make(8, 'İlişkilerimdeki karmik ders ne?', `İlişkilerindeki ana ders, bağ kurarken kendini kaybetmemek ve özgürlüğünü korurken duygusal sorumluluktan kaçmamak. Tanıdık ilişki kalıpları seni ya fazla kontrol etmeye ya da ihtiyaçlarını söylemeden mesafe koymaya çekebilir. Yakınlığı sınır ihlaliyle, bağımsızlığı da yalnızlıkla karıştırmadığında daha dengeli ortaklıklar kurarsın. Karşındaki kişiyi değiştirmeye çalışmak yerine kendi seçimini ve sınırını netleştirmen gerekir. Sevgi senin için ancak karşılıklılık, dürüstlük ve birlikte gelişme olduğunda gerçek bir öğrenme alanına dönüşür.`, chips(data, ['north-node', 'south-node', 'saturn', 'juno', 'venus'])),
    make(9, 'Hangi meslek bana uygun?', `Senin için yalnızca verilen görevi tekrarladığın işler uzun vadede yeterli görünmüyor. ${disciplined ? 'Yönetim, proje koordinasyonu, finansal planlama ve kurumsal danışmanlık' : 'İletişim, eğitim, içerik geliştirme ve satış'} alanlarında güçlü çalışabilirsin. ${cerebral ? 'Bilgiyi düzenleme ve karmaşık bir konuyu anlaşılır hale getirme yeteneğin teknoloji, araştırma veya eğitim tarafını da destekliyor.' : 'İnsanları harekete geçirme ve sonuç alma isteğin operasyon, ekip yönetimi veya girişimcilikte karşılık bulabilir.'} İnsanla sistemi buluşturduğun roller özellikle verimli olabilir. Yetki alanının net olduğu, zamanla uzmanlık ve karar gücü kazanabildiğin meslekler sana daha uygundur.`, chips(data, ['sun', 'mercury', 'mars', 'saturn', 'jupiter'], [angle(data, 'mc')])),
    make(10, 'Devlet mi, özel sektör mü, girişim mi?', `${entrepreneurial ? 'Haritan girişime ve kendi karar alanını kurmaya daha fazla kapı açıyor.' : disciplined ? 'Kuralları ve sorumluluk alanı net kurumlarda güçlü bir temel kurabilirsin.' : 'Özel sektörün hareketli ve sonuç odaklı yapısı sana daha hızlı gelişim sağlayabilir.'} Devlet tarafı güven ve düzen sunar; fakat değişim alanı dar olduğunda motivasyonun azalabilir. Özel sektör deneyim, çevre ve uzmanlık kazanmak için verimli görünüyor. Girişim düşünüyorsan önce sistem, bütçe ve müşteri ihtiyacını öğrenmen önemli. En güçlü modelin, kurumsal deneyimi zamanla daha bağımsız bir çalışma düzenine dönüştürmek olabilir.`, chips(data, ['saturn', 'uranus', 'mars', 'jupiter'], [angle(data, 'mc'), houseChip(data, 6)])),
    make(11, 'Parayı nereden ve nasıl kazanırım?', `Gelirin en çok ${disciplined ? 'uzmanlık, yönetim sorumluluğu ve uzun süre değer üreten çalışmalar' : 'iletişim, proje işleri ve farklı insanları aynı hedefte buluşturduğun çalışmalar'} üzerinden güçlenir. Maaşlı bir yapı başlangıçta güven sağlayabilir; fakat karar alanın ve performansının karşılığı büyüdükçe proje, danışmanlık veya kendi işin daha kazançlı hale gelebilir. ${relational ? 'Ortaklık ve başkalarının kaynaklarını yönetme potansiyelin var; sözleşme ve sınırların net olması gerekir.' : 'Tek gelir kanalına bağlı kalmak yerine tamamlayıcı bir uzmanlık geliştirmek sana esneklik kazandırır.'} Paranı hızlı fırsattan çok ölçülebilir değer ve düzenli birikim büyütür.`, chips(data, ['venus', 'jupiter', 'saturn'], [houseChip(data, 2), houseChip(data, 6)])),
    make(12, 'Zenginleşme potansiyelim var mı?', `Para büyütme potansiyelin var; fakat senin için sürdürülebilir servet modeli kısa yoldan kazanç değil, uzmanlığı ve sorumluluğu zamanla daha yüksek değere dönüştürmek. ${disciplined ? 'Plan, sabır ve düzenli birikim en büyük avantajın.' : 'Fırsatları erken görme ve farklı gelir yolları deneme becerin avantaj sağlıyor.'} Risk tarafında ${hard ? 'kontrolsüz borç, ortak kaynaklarda belirsizlik ve kaybı telafi etmek için acele karar verme' : 'dağınık hedefler ve gelir artınca harcamayı hızla büyütme'} bulunuyor. Şeffaf ortaklıklar, uzun vadeli yatırım disiplini ve kendi uzmanlığına dayanan gelir daha sağlam sonuç verir.`, chips(data, ['jupiter', 'venus', 'saturn', 'pluto'], [houseChip(data, 2), houseChip(data, 8)])),
    make(13, 'Bu hayatta öğrenmem gereken ana ders ne?', `Ana dersin, başkalarının beklentilerine göre güvenli bir rol oynamak yerine kendi isteğini görünür kılmak ve seçiminin sorumluluğunu almak. Alıştığın düzen sana akılcı davranmayı ve topluluğa uyum sağlamayı öğretmiş olabilir; fakat gelişim, kalbinden gelen üretime ve kişisel cesarete alan açtığında başlıyor. ${sensitive ? 'Kırılgan yanını saklamak yerine onun sana öğrettiklerini kabul etmen gerçek gücünü büyütür.' : 'Hata yapma ihtimalini başarısızlık saymadan deneyim kazanman gerekir.'} Sınır, disiplin ve özgünlük aynı yönde çalıştığında hayatın daha anlamlı hale gelir.`, chips(data, ['north-node', 'south-node', 'saturn', 'chiron'], [angle(data, 'asc')])),
    make(14, 'Kuzey Ay Düğümüm bana ne söylüyor?', `Gelişim yönün, tanıdık ve güvenli gelen gözlemci rolünden çıkıp kendi isteğini daha görünür biçimde ortaya koymak. Başkalarının ne düşündüğünü doğru okumakta becerikli olabilirsin; fakat sürekli gruba uyum sağlamak kişisel yaratıcılığını geri plana itebilir. Hayat senden riskli kararlar değil, sana ait bir üretimi sahiplenmeni ve bunun arkasında durmanı istiyor. Alkış beklemeden başlamak, keyif aldığın şeyi ciddiye almak ve kendini küçültmeden paylaşmak içsel yönünü güçlendirir.`, chips(data, ['north-node', 'south-node', 'saturn'], [houseChip(data, north?.house ?? 1)])),
    make(15, 'Geçmiş yaşam etkisi var mı?', `Haritanın sembolik dili, geçmişten taşınmış gibi çalışan güçlü alışkanlıklar bulunduğunu anlatıyor; bu, geçmiş yaşamın somut bir kanıtı değildir. Kalabalığın ihtiyacını öncelemek, duygudan uzaklaşıp akılla kontrol etmek veya sorumluluğu sessizce üstlenmek sana fazlasıyla tanıdık gelebilir. Bu beceriler değerlidir, fakat kişisel arzunu ve yaratıcı cesaretini bastırdığında gelişimini sınırlar. Eski rahat alanını tamamen reddetmen değil, oradaki deneyimi kendi seçtiğin yeni bir yön için kullanman bekleniyor.`, chips(data, ['south-node', 'saturn', 'north-node'], [houseChip(data, 12)])),
    make(16, 'Hangi alanlarda dikkat etmeliyim?', `En çok iş yükünü gereğinden fazla üstlenmek, kontrol edemediğin şeyleri zorla yönetmeye çalışmak ve duygularını son ana kadar içinde tutmak konusunda dikkatli olmalısın. ${hard ? 'Baskı yükseldiğinde sert karar vermek, ilişkide güç mücadelesine girmek veya maddi riski aceleyle büyütmek seni yorabilir.' : 'Sorunları ertelemek ve sınır koymak yerine uyum sağlamaya çalışmak zamanla iç gerilim yaratabilir.'} Görevleri paylaşmak, maddi konularda yazılı ve açık ilerlemek, öfke yükseldiğinde karar için zaman tanımak daha dengeli hareket etmeni sağlar.`, chips(data, ['saturn', 'mars', 'pluto', 'lilith'], [houseChip(data, 8)])),
    make(17, 'Stres altında hangi yaşam alanlarım daha hassas olabilir?', `Stres yükseldiğinde iş yükü, kontrol ihtiyacı, yakın ilişkiler ve ortak maddi sorumluluklar daha hassas hale gelebilir. ${deep ? 'Duygularını içeride tutup her şeyi tek başına çözmeye çalışman, yalnız kalma ihtiyacını artırabilir.' : 'Zihnin çok hızlandığında aynı anda fazla seçeneği yönetmek ve dinlenmeden devam etmek seni dağıtabilir.'} ${relational ? 'İlişkide belirsizlik veya güven eksikliği olduğunda bunu diğer yaşam alanlarına taşıma eğilimin var.' : 'Kişisel alanın daraldığında sabırsız veya mesafeli davranabilirsin.'} Burada hastalık tahmini değil, baskı altında hangi davranış kalıplarını erken fark etmen gerektiği anlatılıyor.`, chips(data, ['moon', 'mars', 'saturn', 'pluto'], [houseChip(data, 6), houseChip(data, 12)])),
  ];
}

export const questionWordCount = (item: PremiumReportAnalysis) => item.text.trim().split(/\s+/).length;
