import { router, type Href } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors } from '@/constants/theme';
import { isSafeQuestionId } from '@/features/questions/domain';
import { useLocale, usePalette } from '@/localization';
import type { SocialNotificationItem } from './api';
import { formatNotificationCount, groupSocialNotifications, type SocialNotificationRow } from './notificationPresentation';

function relativeTime(value:string,m:{now:string;minuteAgo:string;minutesAgo:string;hourAgo:string;hoursAgo:string;yesterday:string;daysAgo:string},now=Date.now()){const minutes=Math.floor(Math.max(0,now-Date.parse(value))/60000);if(minutes<1)return m.now;if(minutes===1)return m.minuteAgo;if(minutes<60)return m.minutesAgo.replace('{n}',String(minutes));const hours=Math.floor(minutes/60);if(hours===1)return m.hourAgo;if(hours<24)return m.hoursAgo.replace('{n}',String(hours));const days=Math.floor(hours/24);return days===1?m.yesterday:m.daysAgo.replace('{n}',String(days));}
function openNotification(item:SocialNotificationRow){if(item.type==='private_message'&&item.conversationId){router.push({pathname:'/private-chat',params:{conversationId:item.conversationId,...(item.handle?{handle:item.handle}:{})}} as Href);return;}if(item.type==='soulmate_match')router.push('/soulmate' as Href);if(item.type==='question_answered'&&isSafeQuestionId(item.questionId))router.push(`/questions/${item.questionId}` as Href);}

export function SocialNotificationsPanel({notifications}:{notifications:SocialNotificationItem[]}){
 const {locale,messages}=useLocale();const palette=usePalette();const m=messages.socialUi;const rows=groupSocialNotifications(notifications);
 return <View style={styles.section}><Text style={[styles.heading,{color:palette.navy}]}>{m.notifications}</Text>{!rows.length?<Text style={[styles.empty,{color:palette.muted}]}>{m.noNotifications}</Text>:<View style={styles.list}>{rows.map((item)=>{const isMessage=item.type==='private_message';const isQuestion=item.type==='question_answered';const detail=isQuestion?m.questionDetail:isMessage?(item.handle?`@${item.handle} ${m.messageDetail}`:m.genericMessage):item.type==='soulmate_match'?(item.handle?`@${item.handle} ${m.matchDetail}`:m.genericMatch):m.genericNotification;const disabled=(isMessage&&!item.conversationId)||(isQuestion&&!isSafeQuestionId(item.questionId))||(!isMessage&&!isQuestion&&item.type!=='soulmate_match');return <Pressable disabled={disabled} key={isMessage&&item.conversationId?`conversation:${item.conversationId}`:item.notificationId} onPress={()=>openNotification(item)} style={({pressed})=>[styles.row,{backgroundColor:item.unreadCount>0?palette.sapphireSoft:palette.surface,borderColor:palette.border},pressed&&styles.pressed]}><View style={[styles.icon,{backgroundColor:palette.background}]}><Text style={styles.iconText}>{isMessage?'💬':'✦'}</Text></View><View style={styles.copy}><View style={styles.titleRow}><Text style={[styles.title,{color:palette.navy}]}>{isQuestion?m.questionReady:isMessage?m.newMessage:item.type==='soulmate_match'?m.newMatch:m.notification}</Text>{isMessage&&item.unreadCount>0?<View style={styles.countBadge}><Text style={styles.countBadgeText}>{formatNotificationCount(item.unreadCount)}</Text></View>:!item.read?<View style={styles.dot}/>:null}</View><Text style={[styles.detail,{color:palette.navy}]}>{detail}</Text><Text style={[styles.time,{color:palette.muted}]}>{relativeTime(item.latestCreatedAt,m)}</Text></View></Pressable>;})}</View>}</View>;
}
const styles=StyleSheet.create({section:{gap:10},heading:{fontSize:13,fontWeight:'900',letterSpacing:1.1},empty:{fontSize:14,lineHeight:20,paddingHorizontal:2},list:{gap:8},row:{alignItems:'center',borderRadius:16,borderWidth:1,flexDirection:'row',gap:11,minHeight:78,padding:12},pressed:{opacity:.72},icon:{alignItems:'center',borderRadius:19,height:38,justifyContent:'center',width:38},iconText:{fontSize:18},copy:{flex:1,gap:2,minWidth:0},titleRow:{alignItems:'center',flexDirection:'row',gap:7},title:{flexShrink:1,fontSize:15,fontWeight:'900'},dot:{backgroundColor:colors.danger,borderRadius:4,height:8,width:8},countBadge:{alignItems:'center',backgroundColor:colors.danger,borderRadius:10,justifyContent:'center',minHeight:20,minWidth:20,paddingHorizontal:6},countBadgeText:{color:colors.white,fontSize:11,fontWeight:'900'},detail:{fontSize:14,lineHeight:20},time:{fontSize:11,fontWeight:'700'}});
